bigData/Data/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='Data'
urlpatterns = [
    path('', views.searchPage,name='index'),
    path('rept/',views.respond,name='respond')
]

bigData/bigData/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Data.urls")),

]

bigData/Data/models.py
from django.db import models

# Create your models here.
class Data1(models.Model):
    id = models.CharField(primary_key=True, max_length=255)
    岗位 = models.CharField(max_length=32, blank=True, null=True)
    地点 = models.CharField(max_length=32, blank=True, null=True)
    薪资 = models.CharField(max_length=32, blank=True, null=True)
    工作经验 = models.CharField(max_length=32, blank=True, null=True)
    学历 = models.CharField(max_length=32, blank=True, null=True)
    公司 = models.CharField(max_length=32, blank=True, null=True)
    技能 = models.CharField(max_length=32, blank=True, null=True)
    区间最小薪资千 = models.IntegerField(db_column='区间最小薪资千', blank=True, null=True)
    城市地区 = models.CharField(max_length=32, blank=True, null=True)
    城市 = models.CharField(max_length=32, blank=True, null=True)
    地区 = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'data1'
        verbose_name = "Python岗位数据"
        verbose_name_plural = "Python岗位数据"



    def str(self):
        return str(self.id)
class Search(models.Model):
    岗位 = models.CharField(max_length=255, blank=True, null=True)
    地点 = models.CharField(max_length=32, blank=True, null=True)
    薪资 = models.CharField(max_length=32, blank=True, null=True)
    工作经验 = models.CharField(max_length=32, blank=True, null=True)
    学历 = models.CharField(max_length=32, blank=True, null=True)
    公司 = models.CharField(max_length=32, blank=True, null=True)
    技能 = models.CharField(max_length=32, blank=True, null=True)
    区间最小薪资千 = models.IntegerField(db_column='区间最小薪资千', blank=True, null=True)
    城市地区 = models.CharField(max_length=32, blank=True, null=True)
    城市 = models.CharField(max_length=32, blank=True, null=True)
    地区 = models.CharField(max_length=32, blank=True, null=True)
    class Meta:
        managed =True
        db_table = 'search'

bigData/Data/views.py
from django.http import HttpResponse
from django.shortcuts import render,HttpResponse
from . import service
from  django.shortcuts import render
from .models import Data1
from .models import Search
import pandas as pd

# from .searchFun import start_search
def searchPage(request):
     return render(request, 'index.html')
def respond(request):
    text=request.POST['搜索内容']
    db=Data1.objects.all()
    po_list=[]
    for i in db:
         if text in i.岗位:
             service.addsearch(i)
    df = pd.read_excel("中国城市经纬度数据表.xlsx")
    from django.db import connection
    sql = "select 工作经验,count(*) as b from search group by 工作经验 order by b desc "
    with connection.cursor() as cur:
        cur.execute(sql)
    data_list = cur.fetchall()
    sql = "select 学历,avg(区间最小薪资千) as b from data1 group by 学历 order by b desc"
    with connection.cursor() as cur:
        cur.execute(sql)
    data_list1 = cur.fetchall()
    sql = "select 岗位 as b from search "
    with connection.cursor() as cur:
        cur.execute(sql)
    data_list2 = cur.fetchall()
    sql = "select 技能  from search"
    with connection.cursor() as cur:
        cur.execute(sql)
    data_list3 = cur.fetchall()
    sql = "select 城市,avg(区间最小薪资千) as b from data1  group by 城市 order by b desc "
    with connection.cursor() as cur:
        cur.execute(sql)
    data_list5 = cur.fetchall()
    sql = "select 公司,count(*) as b,round(avg(区间最小薪资千),1) as b from search  group by 公司 order by b desc"
    with connection.cursor() as cur:
        cur.execute(sql)
    data_list6 = cur.fetchall()
    x_bar1=[]
    y_bar1=[]
    x_bar2 = []
    y_bar2 = []
    for i in  data_list:
        x_bar1.append(i[0])
        y_bar1.append(round(i[1],1))

    for i in  data_list1:
        x_bar2.append(i[0])
        y_bar2.append(round(i[1],1))

    list1 = []
    for i in data_list2:
        a = i[0].split(";")

        for j in i[0].split(";"):
            j = j.replace('python', 'Python')
            j = j.replace('Python开发工程师', 'Python开发')
            list1.append(j)
    dict = {}
    for key in list1:
        dict[key] = dict.get(key, 0) + 1
    a1 = sorted(dict.items(), key=lambda x: x[1], reverse=True)
    s_pie= []
    for i in a1[0:6]:
        s_pie.append({"name": i[0], "value": i[1]})

    list1 = []
    for i in data_list3:
        a = i[0].split(";")
        for j in i[0].split(";"):
            j = j.replace('[', '')
            j = j.replace(']', '')
            j = j.replace(' ', '')
            j = j.replace("'", '')
            list1.append(j)
    dict = {}
    for key in list1:
        dict[key] = dict.get(key, 0) + 1
    a1 = sorted(dict.items(), key=lambda x: x[1], reverse=True)
    s_pie2 = []
    for i in a1[0:6]:
        s_pie2.append({"name": i[0], "value": i[1]})
    map=[]
    for i in data_list5:
        for j in df.itertuples():
            if i[0] == j[1]:
                map.append({"name": i[0], "value": [j[3], j[2], i[1]]})
    print(map)
    table = []
    for i in data_list6[0:10]:
        table.append({"name": i[0], "value1": i[1], "value2": i[2]})
    data_bar1={
        "x_bar1":x_bar1,
        "y_bar1":y_bar1,
        "x_bar2": x_bar2,
        "y_bar2": y_bar2,
        "s_pie" :s_pie,
        "s_pie2": s_pie2,
        "map":map,
        "table":table
    }

    return render(request, 'result.html', data_bar1)

bigData/templates/index.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>开始搜索</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="../static/css/style.css">
      <!-- Responsive-->
      <link rel="stylesheet" href="../static/css/responsive.css">
      <!-- fevicon -->
      <link rel="icon" href="../static/images/fevicon.png" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="../static/css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="../static/css/font-awesome.css">
      <!-- owl stylesheets -->
      <link href="https://fonts.googleapis.com/css?family=Orbitron:400,500,600,700|Poppins:400,700&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="../static/css/owl.carousel.min.css">
      <link rel="stylesoeet" href="../static/css/owl.theme.default.min.css">
      <link rel="stylesheet" href="../static/css/jquery.fancybox.min.css" media="screen">
   </head>
   <body>

      <div class="banner_section layout_padding">
         <div id="main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <div class="banner_taital">
                        <h1 class="banner_taital">Let’s start seek</h1>
                        <p class="banner_text"> </p>
                     </div>
                     <div class="play_now_bt"><a href="#">Job information search visualization</a></div>
                     <h1 class="Music_text">work</h1>
                     <form action="{%url 'Data:respond'%}" method="POST" class="example" >
                        {%  csrf_token %}
                       <input type="text" placeholder="Please enter the search content...." name='搜索内容'>
                       <button type="submit"><i class="fa fa-search"></i></button>
                     </form>
                  </div>
                  <div class="container-fluid">
                     <h4 class="number_text active">01<span style="text-align: right; float: right;">03</span></h4>
                  </div>
               </div>
       </div>
            <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
              <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
              <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
      <!-- banner section end -->
      <!-- news section start -->
      <div class="news_section layout_padding">
         <div class="container">
            <div class="news_taital_main">
               <h1 class="latest_text">高薪水</h1>
               <div class="seemor_bt"><a href="#">更多</a></div>
            </div>
         </div>
      </div>
      <div class="news_section_2">
         <div class="container">
            <div class="down_arrow"><img src="../static/images/down-arrow.png"></div>
            <div class="row">
               <div class="col-lg-3 col-sm-6">
                  <div class="images_main">
                     <div class="image_1"><img src="../static/images/img-1.png" class="image_1"></div>
                     <div class="text_main">
                        <h2 class="business_text">高薪工作有哪些？</h2>
                        <p class="date_text">03/01/2023</p>
                     </div>
                     <p class="ipsum_text">高薪的工作中这几个职业占一大半（如果奶茶店、煎饼摊这些老板不算为职业，员工算为职业）：医生、律师、金融行业、IT行业、工程师、市场营销、运营、销售、艺术设计。 虽然说行行能出状元，但是如果一个行业只有最靠前的1%收入特别高</p>
                     <div class="seemor_bt_1"><a href="#">查找更多</a></div>
                  </div>
               </div>
               <div class="col-lg-3 col-sm-6">
                  <div class="images_main">
                     <div class="image_1"><img src="../static/images/img-2.png" class="image_1"></div>
                     <div class="text_main">
                        <h2 class="business_text">2022就业市场会有多糟糕？</h2>
                        <p class="date_text">03/01/2023</p>
                     </div>
                     <p class="ipsum_text">今年各大互联网公司都在降本增效，不少往年的互联网大厂都在寻找新的经济增长点。相比起往年，今年的就业环境其实非常差。2022年其实是一个重要的分割点。大体上看，今年的就业市场供需关系发生了很大变化。也就是说，从候选人的角度看，如果你想拿到一个offer，就必须pk掉大多数比你优秀的人。</p>
                     <div class="seemor_bt_1"><a href="#">查找更多</a></div>
                  </div>
               </div>
               <div class="col-lg-3 col-sm-6">
                  <div class="images_main">
                     <div class="image_1"><img src="../static/images/img-3.png" class="image_1"></div>
                     <div class="text_main">
                        <h2 class="business_text">最高法：坚决反对就业歧视，推动高校毕业生平等就业</h2>
                        <p class="date_text">03/01/2023</p>
                     </div>
                     <p class="ipsum_text">12月27日，最高人民法院发布《关于为稳定就业提供司法服务和保障的意见》（以下简称《意见》）。《意见》指出，依法支持高校毕业生就业，促进多渠道灵活就业。妥善审理平等就业权纠纷案件，依法纠正用人单位因性别歧视、地域歧视等不予招录、拒绝签订劳动合同的行为，破除各种不合理限制，推动高校毕业生平等就业、多渠道灵活就业创业。</p>
                     <div class="seemor_bt_1"><a href="#">查找更多</a></div>
                  </div>
               </div>
               <div class="col-lg-3 col-sm-6">
                  <div class="images_main">
                     <div class="image_1"><img src="../static/images/img-4.png" class="image_1"></div>
                     <div class="text_main">
                        <h2 class="business_text">什么是面试？面试有哪些技巧呢？</h2>
                        <p class="date_text">03/01/2023</p>
                     </div>
                     <p class="ipsum_text">面试是以通过书面、面谈或线上交流的形式来考察一个人的工作能力和应变能力等综合素质的对应聘者的考核。面试给应聘者和公司提供了交流的机会，同时也让公司从应聘者的表现中决定是否应聘。其中，很多学历高、经验足的求职人员并没有在面试过程中凭借自身优势脱颖而出，由此，应用面试技巧作为面试的助推器是很有必要的。</p>
                     <div class="seemor_bt_1"><a href="#">查找更多</a></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- news section end -->

      <div class="news_section layout_padding">
         <div class="container">
            <div class="news_taital_main">
               <h1 class="latest_text">高薪工作</h1>
               <div class="seemor_bt"><a href="#">查找更多</a></div>
            </div>
         </div>
      </div>

      <script src="../static/js/jquery.min.js"></script>
      <script src="../static/js/popper.min.js"></script>
      <script src="../static/js/bootstrap.bundle.min.js"></script>
      <script src="../static/js/jquery-3.0.0.min.js"></script>
      <script src="../static/js/plugin.js"></script>
      <!-- sidebar -->
      <script src="../static/js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="../static/js/custom.js"></script>
      <!-- javascript -->
      <script src="../static/js/owl.carousel.js"></script>
      <script src="../static/js/jquery.fancybox.min.js"></script>
   </body>
</html>

bigData/templates/respond.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索结果</title>
</head>
<body>
{% for i in resp %}
<h3>{{i}}
</h3>
{% endfor %}
</body>
</html>